### PR TITLE
0.6 alpha

### PR DESCRIPTION
**Pull request by NikitaEgorov**
Fix for Sphinx 1.5.1

### CODE REVIEW

**Comment by ericholscher** [comment]
Another option is to not ship these files and pull them from Sphinx itself.

**Comment by agjohnson** [comment]
Yeah, that seems like a better approach. I'm not sure there's much reason for the files to be vendored at all, do you?

**Comment by ericholscher** [comment]
Not off hand -- probably was just easier than trying to figure out the path from Sphinx.

**Comment by ericholscher** [comment]
I'm actually thinking these aren't used, since we point at them directly on the RTD servers, and can probably be deleted.

**Comment by ericholscher** [comment]
The bigger issue is it there are multiple versions of these files that are backwards incompat, our pattern of hosting them ourselves might be worth re-thinking. It's an optimization, but if it breaks stuff it's not worth doing.

**Comment by ericholscher** [comment]
Closing this, as I think #11 addresses the root issue.

**Pull request closed without merging**
